### ISSUE TITLE
Navigation HTML

### ISSUE THREAD

**Issue by jmaldia** [chingu-voyage4/Toucans-Team-5#1]
As a user 
I want a navigation bar
so that I can quickly get to the resource I need

**Comment by jmaldia** [comment]
https://dha4w82d62smt.cloudfront.net/items/0V1J0M1q1Z272s3j262L/Image%202018-03-11%20at%202.41.48%20PM.png?X-CloudApp-Visitor-Id=2616f30cd10ba32de9b7e6498ac7e44b&v=cf964adb

**Comment by starkspark** [comment]
-"Product", "Pricing", "Docs", "Sign In", "Get Started" Links
- Hover Color Change Feature
- Hamburger Menu Responsiveness
