### ISSUE TITLE
Bottom Navigiation

### ISSUE THREAD

**Issue by jmaldia** [chingu-voyage4/Toucans-Team-5#16]
As a User
I want to be able to navigate to other parts of the site 
When I go to the bottom of the page

**Comment by jmaldia** [comment]
http://screen.ac/1l2I120H1m1V

**Comment by starkspark** [comment]
- "About Us", "Terms", "Privacy", "The Composition", "Contact Links"
- NO hover color change feature (unlike top navigation)
