### ISSUE TITLE
Chat box/button HTML

### ISSUE THREAD

**Issue by jmaldia** [chingu-voyage4/Toucans-Team-5#9]
As a user
I want to a place to chat with someone 
so that I can learn more about the product/service in real time

**Comment by starkspark** [comment]
- Open & Close icons
- "New Conversation" box shadow on hover
- GIF, emoji, and file icons
-- 1st two open a window full of gifs & emoji; last opens finder
- Conversation thread's fill color becomes darker, a light grey, on hover
- Located on bottom right hand corner for easy access (fixed display)
